//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RangoFechas
    {


        public string Activo { get; set; }
        public int Tickets_Registrados { get; set; }
        public int Tickets_Abiertos { get; set; }
        public int Tickets_Cerrados { get; set; }

    }
}
