//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Solicitudes
    {
        [Key]
        public int IdSolicitud { get; set; }
        public string Ubicacion { get; set; }
        public string Correo { get; set; }
        public string Departamento { get; set; }
        public string Telefono { get; set; }
        public string Tipo_solicitud { get; set; }
        [AllowHtml]
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_levantamiento { get; set; }
        public string Estatus { get; set; }
        public string Asunto { get; set; }
        public string Conclusion { get; set; }
        public string SLA_C_A { get; set; }
        public string SLA_C_M { get; set; }
        public string SLA_C_B { get; set; }
        public string Responsable { get; set; }
        public string Categoria { get; set; }
        public Nullable<System.DateTime> Fecha_cierre { get; set; }
        public string Activo { get; set; }
        public string Subactivo { get; set; }
        public Byte Vencido { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
    }
}
